server:
  port: 8077
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
spring:
  profiles:
    active: '@activatedProperties@'
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
application:
  tomcat-context-path: /lms
  inbound-request-logging: true
logging:
  level:
    org:
      springframework: ERROR
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: /data/tomcat/log/lms/lms.log
cc:
  prefix: pos
app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000
aes:
  secretKey: lms123
  initializationVector: coachbar123
